language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
install:
  - pip install numpy scipy cython
  - pip install pandas
  - pip install sklearn
  - pip install mdtraj
  - pip install nose
  - pip install coverage
  - pip install -e .

script:
  # Your test script goes here
  - nosetests --with-coverage -v

after_success:
  - bash <(curl -s https://codecov.io/bash)

